spring:
  datasource: ## Spring DATASOURCE
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456!a
  jpa: ## Hibernate Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      ddl-auto: validate # Hibernate ddl auto (create, create-drop, validate, update)
  flyway: ## flyway
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    user: root # should not use root
    password: 123456!a
  mail:
    host: smtp.tinhvan.com
    username: ngocdc@tinhvan.com
    password: Djr01001@
    port: 587
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.tinhvan.com # trust ssl host
          timeout: 30000
          connecttimeout: 30000
          writetimeout: 30000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

file:
  avatar-upload-dir: F:\TVJ\file_upload\avatar\
  default-avatar-file-name: default_avatar.jpg

date-time-pattern:
  sticky: yyyyMMddhhmmss

server: ## use for embedded tomcat server port
  port: 8082

jwt:
  token:
    validity-in-second: 7200 # 3600 = 1 * 60 * 60 = 1 hours
    secret: TVJ2019@

forgot-password:
  token-expired-duration-in-hour: 2
  mail-subject: "Forgot password mail verification"
  mail-template: "This is mail verification for user:<b><font color=''red''> {0} </font></b><br>Please click on <a href=''http://{1}:{2}/password-recover-confirm-token/{3}''>this link</a> to update your password."
  max-login-failed-count: 5
  
cron-expression: # (*) means match any, (*/X) means "every X"
  forgot-password: "0 0/60 * * * ?"
  validate-last-logout-by-token: "0 0/5 * * * ?"

account-is-locked:
  mail-subject: "Your account is locked"
  mail-template: "Account <b><font color=''red''>{0}</font></b> is locked at {1}. Please contact administrator to get support or do forgot password process to recover password."

logging:
  config: src/main/resources/logback-production.xml

front-end-host: "192.168.43.189"
