spring:
  datasource: ## Spring DATASOURCE
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456!a
  jpa: ## Hibernate Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      ddl-auto: validate # Hibernate ddl auto (create, create-drop, validate, update)
  flyway: ## flyway
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    user: root # should not use root
    password: 123456!a
  mail:
    host: smtp.tinhvan.com
    username: ngocdc@tinhvan.com
    password: Djr01001@
    port: 587 #443
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.tinhvan.com # trust ssl host
          timeout: 20000
          connecttimeout: 20000
          writetimeout: 20000

server: ## use for embedded tomcat server port
  port: 8080

jwt:
  token:
    validity: 3600 # 3600 = 1 * 60 * 60 = 1 hours
    secret: TVJ2019@
