spring:
  datasource: ## Spring DATASOURCE
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456!a
  jpa: ## Hibernate Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      ddl-auto: validate # Hibernate ddl auto (create, create-drop, validate, update)
  flyway: ## flyway
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    user: root # should not use root
    password: 123456!a

server: ## use for embedded tomcat server port
  port: 8080
