spring:
  datasource: ## Spring DATASOURCE
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456!a
  jpa: ## Hibernate Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      ddl-auto: validate # Hibernate ddl auto (create, create-drop, validate, update)
  flyway: ## flyway
    url: jdbc:mysql://localhost:3306/tvj_internal_db?useSSL=false&allowPublicKeyRetrieval=true
    user: root # should not use root
    password: 123456!a
  mail:
    host: smtp.tinhvan.com
    username: ngocdc@tinhvan.com
    password: Djr01001@
    port: 587 #443
    properties:
      mail:
        smpt:
          auth: true
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.tinhvan.com # trust ssl host
          timeout: 30000
          connecttimeout: 30000
          writetimeout: 30000

server: ## use for embedded tomcat server port
  port: 8080

jwt:
  token:
    validity: 3600 # 3600 = 1 * 60 * 60 = 1 hours
    secret: TVJ2019@

forgot-password:
  token-expired-duration-in-hour: 1
  mail-subject: "Forgot password mail verification"
  mail-template: "This is mail verification for user: <b><font color=''red''>{0} {1}</font></b><br>Please click on <a href=''http://{2}:{3}/user/password-recover-confirm-token?token={4}''>this link</a> to update your password."
  cron-expression: "0 0/1 * * * ?"